### PR TITLE
Upgrade axis2 version to the 1.6.1.wso2v24

### PR DESCRIPTION
**Pull request by GDRDABARERA**

### CODE REVIEW

**Comment by chanikag** [comment]
@GDRDABARERA , have you run unit tests after version upgrade of axis2? Because we have encountered some test failures after axis2 version upgrade as in [1]

[1] http://wso2-oxygen-tank.10903.n7.nabble.com/Test-failure-in-axis2-transport-when-the-axis2-version-is-upgraded-td156021.html

**Comment by malithie** [comment]
@chanikag,
I verified and all unit test cases are passing.
Can we merge this PR

**Comment by malithie** [comment]
@GDRDABARERA ,

As chanika mentioned unit tests are failing.
Please verify and resend the PR

**Comment by chanikag** [comment]
Closing PR for now.

**Pull request closed without merging**
